name: Code Analysis

on:
  push:

env:
  node-version: 16.x

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'black'

  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'flake8'

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'isort'

  pyroma:
    name: pyroma
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'pyroma'

  zpretty:
    name: zpretty
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Run check
        uses: plone/code-analysis-action@v2
        with:
          check: 'zpretty'

  frontend:
    name: Check frontend code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install pnpm
        run: |
          npm i -g pnpm
          npm update -g pnpm
          pnpm --version

      - name: Install Frontend
        run: pnpm i  --frozen-lockfile

      - name: eslint-check
        run: pnpm lint

      - name: prettier
        run: pnpm prettier
