
name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
        plone:
          - "6.0-latest"

    steps:
    - uses: actions/checkout@v3

    - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
      id: setup
      uses: plone/setup-plone@v2.0.0
      with:
        python-version: ${{ matrix.python }}
        plone-version: ${{ matrix.plone }}

    # Install plone.distribution with test extras
    - name: Install plone.distribution
      run: |
        pip install ".[test]"

    # test
    - name: Test Codebase
      run: |
        pytest --disable-warnings
